var GAME_LEVELS = [
  ["                                                         $           yyyy       ",
   "   e    yyy                            $$$$$$$            o      $ yyy          ",
   "      yyyyyyyy                                           ooo     yyyyyyy        ",
   "        yyyy   e               x   x    x  x x x   x    ooooo             e     ",
   " $      $  xxxxxxxxxxxxxx  x   x  xx xx x x $  x     xxxxxxxxxx $      $        ",
   "       xxx              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!                o",
   "  o xxx      yyyyyy      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!               xx",
   "x o           yyyyyy        e                       !!!!!!      $            xxx",
   "  o             yyyyy               o o      xx                  $  o       xxxx",
   "xxxx   x  xx                $                                    e  o      xxxxx",
   "               xxx     o           xxxxx   e      $   xx            o     xxxxxx",
   " xxxx!!!!xxx          xxx                        xx        xx       o   xxxxxxxx",
   " xxxx!!!!xxx e            xxxx     $      o$o         yyy     x     x  x     xxx",
   " xx  xxxx      e        o         xxxx      $      yyyyyy      x!!!!!!x      xxx",
   " xx                              $       xxxxx    yyyyyyx      xxxxxxxx      xxx",
   " xx            $        o       x        x!!!x       yy                      xxx",
   " xx  @    $  x x     xxxxx      x    $$              $ x   $     xxxxx       xxx",
   " xxxxxxxxxxxxx!xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx  o  xxxxxxx   xxxxxxxxxxx",
   "             xxxx             x   x                  x   x x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx               e                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "    e                                  xxxxxxxxxx!!x         x       e                            o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   " $       $                                       x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   " oo     ooo                           $          xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   " xx!!!!!xxx         x  x   x   x     ooo                     xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   " xxxxxxxxxx $ $                    xxxxx                      xx!!!!!!!!!!!xx            |     x                  ",
   "            xxxx  $                                   xx       xxxx!!!!!xxxx      $            x                  ",
   "                  xxx  $                       x     x            xxxxxxx        xxx         xxx                  ",
   "                       xxx                     x     x                           x x         x x                  ",
   "  e                          $                 x     x           e                 x         x                    ",
   "                           xxx                 x$    x                             xx        x                    ",
   "                        xx                     xx    x                             x         x                    ",
   "                  $            o  e  o         x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x      e        x   x         x         x                    ",
   "              xx     xx         x   x          x    $x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x     o         x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   " || x x  ||  x         x  ||   xx o xx   |||   x$    x  |            x     o o   x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!xxxxxx    =     x x          x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o           o     xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x         e      o    xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                    e                                                         ",
   "                                        o                                                                     ",
   "                                                                      $                                       ",
   "                                        x              $           xxxxx                                      ",
   "                                        x           xxxxx                        $                            ",
   "                                        x                                    xxxxx                            ",
   "                                       $x       e                                                             ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx     e                          ",
   "                                     $ x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx    e                       ",
   "                                      x   x                 x   $      x      x!!!x                           ",
   "                      e              $x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                e                     x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                     $x   x           x                     xxx                               ",
   "                                     xx   xxooo       x               e                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "              e                       x   x           x           x!!!x                              ====     ",
   "                                     $x   xo   = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx         ===       ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx    ===           $   ",
   "  xxx                         x    $x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x $$o                                      xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x    e        $             x           x                              x   x                             x  ",
   "  x                           xx          x        oooo      oooo        x x x                             x  ",
   "  x     e           $                     x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx           $         x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx   e    xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["              e                                                                                   xxx x       ",
   "              e                                                                                       x       ",
   "                                                                                                  xxxxx       ",
   "                   e                                                                              x           ",
   "                                  o                                                               x xxx       ",
   "                          o       xxxxx           o       ooo                                     x x x       ",
   "                   $$                            xxxxxx   xxxxx                              o o oxxx x       ",
   "                   xxx                     ooo                        $$   $$$   $$$   $$$            x       ",
   "       !  o  !                e            xxxxx              xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x            $           oooo                    x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x          xxxxx                    xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                           xxxxx                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                   xxxx           xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                         $                                          e            e                            ",
   "          o              xxx                              xx                                                  ",
   "                                                                                     e                        ",
   "                        e                             $             e                                         ",
   "                   $o          $o                     xx                                                      ",
   "                   xxx         xxx                    e                                                       ",
   "     ====         e                                                                                           ",
   "                          o                    e                                x      x                      ",
   "             $ o         e                                xx     xx                    e                      ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "   = =    $                                                      ||                                           ",
   "  xxxxxxxxxxx    $    $      $     $             e                                                            ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                       e                        x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx      $                        o                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x ||||||||||||||||||| xxx     |||||||||||||||||||||         ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
